### ISSUE TITLE
Support Rack-based apps

### ISSUE THREAD

**Issue by aw** [bonsaiben/nightlight#3]
This is a pretty awesome project! As mentioned in a previous discussion, it would be really cool if this supported Rack-based applications :+1: .

I currently use Grape / Sinatra, but I think basic Rack support would automatically be supported by those frameworks.

A good place to start would be explicitly requiring the `activerecord` and `rack` gems in the gemspec:

```
spec.add_dependency 'rack', '>= 1.5.0'
spec.add_dependency 'activerecord'
```

Thanks!

EDIT: activerecord ;)

**Comment by bonsaiben** [comment]
Thanks!

Some considerations we'll need to make for this:
- keeping the memory footprint as small as possible
- how each framework defines routes differently (for detecting new pages)
